ARG BUILD_FROM=ghcr.io/home-assistant/amd64-base:latest
FROM $BUILD_FROM

RUN apk add --no-cache python3 py3-pip sqlite

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir --break-system-packages -r requirements.txt

COPY app/ ./app/
COPY run.sh ./

RUN mkdir -p /data
RUN chmod +x run.sh

EXPOSE 8100

LABEL io.hass.name="Access Control System" \
      io.hass.description="ESP32 Access Control System" \
      io.hass.version="1.0.0"

CMD ["./run.sh"]
